In [ ]:
#Basic Setting up environment and testing for running

In [1]:
import numpy as np
import gym
import time
import random
from time import sleep

In [2]:
env = gym.make("Taxi-v3")

In [3]:
action_size = env.action_space.n
state_size = env.observation_space.n

print ('State Space : ',state_size)
print ('Action space : ',action_size)

State Space :  500
Action space :  6


In [4]:
#test if it is running or not

In [5]:
'''
env.reset()
for _ in range(10):
    env.render()
    time.sleep(.05)
    env.step(env.action_space.sample()) # take a random action
    env.reset()
env.close()
'''

'\nenv.reset()\nfor _ in range(10):\n    env.render()\n    time.sleep(.05)\n    env.step(env.action_space.sample()) # take a random action\n    env.reset()\nenv.close()\n'

In [6]:
# Build simple RL

In [8]:
total_episodes = 8000        
max_steps = 90               
gamma = 0.99                 

# Exploration parameters
epsilon = 1.0                
max_epsilon = 1.0            
min_epsilon = 0.01            
decay_rate = 0.005           
learning_rate = 0.85

qtable = np.zeros((state_size, action_size)) 
print(qtable)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [9]:
# List of rewards
rewards = []

# 2 For life or until learning is stopped
for episode in range(total_episodes):
    # Reset the environment
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        explore_exploit = random.uniform(0, 1)
        
        if explore_exploit > epsilon:
            action = np.argmax(qtable[state,:])

        else:
            action = env.action_space.sample()
        
        new_state, reward, done, info = env.step(action)

        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        # qtable[new_state,:] : all the actions we can take from new state
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        
        total_rewards += reward
                
        state = new_state
        
        if done == True: 
            break
        
    # We reduce epsilon because we don't want the agent just explore over and over again but never exploit
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
    rewards.append(total_rewards)

print ("Score over time: " +  str(sum(rewards)/total_episodes))
#print(qtable)

Score over time: -1.298


In [10]:
"""Display and evaluate agent's performance after Q-learning."""
env.reset()
display_episodes=10

total_epochs, total_penalties = 0, 0

for _ in range(display_episodes):
    state = env.reset()
    epochs, penalties, reward = 0, 0, 0
    
    done = False
    
    while not done:
        action = np.argmax(qtable[state])
        state, reward, done, info = env.step(action)

        if reward == -10:
            penalties += 1

        epochs += 1
        env.render()
        print(f"Timestep: {epochs}")
        print(f"State: {state}")
        print(f"Action: {action}")
        print(f"Reward: {reward}")
        sleep(0.15) # Sleep so the user can see the 

    total_penalties += penalties
    total_epochs += epochs

env.close()

print(f"Results after {display_episodes} episodes:")
print(f"Average timesteps per episode: {total_epochs / display_episodes}")
print(f"Average penalties per episode: {total_penalties / display_episodes}")

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
Timestep: 1
State: 124
Action: 2
Reward: -1
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
Timestep: 2
State: 224
Action: 0
Reward: -1
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
Timestep: 3
State: 244
Action: 2
Reward: -1
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
Timestep: 4
State: 264
Action: 2
Reward: -1
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
Timestep: 5
State: 284
Action: 2
Reward: -1
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
Timestep: 6
State: 184
Action: 1
Reward: -1
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
Timestep: 7
State: 84
Action: 1
Reward: -1
+---------+
|R: | : :G|
| : | : : |
| :

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
Timestep: 4
State: 251
Action: 3
Reward: -1
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
Timestep: 5
State: 231
Action: 3
Reward: -1
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
Timestep: 6
State: 211
Action: 3
Reward: -1
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
Timestep: 7
State: 311
Action: 0
Reward: -1
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
Timestep: 8
State: 411
Action: 0
Reward: -1
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
Timestep: 9
State: 419
Action: 4
Reward: -1
+---------+
|R: | : :G|
| : | : : |
| : : : : |
|_| : | : |
|Y| : |B: |
+---------+
  (North)
Timestep: 10
State: 319
Action: 1
Reward: -1
+---------+
|R: | : :G|
| : | : : |

+---------+
|R: | : :G|
| : | : : |
|_: : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
Timestep: 9
State: 218
Action: 0
Reward: -1
+---------+
|R: | : :G|
| : | : : |
| : : : : |
|_| : | : |
|Y| : |B: |
+---------+
  (South)
Timestep: 10
State: 318
Action: 0
Reward: -1
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
Timestep: 11
State: 418
Action: 0
Reward: -1
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Dropoff)
Timestep: 12
State: 410
Action: 5
Reward: 20
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
Timestep: 1
State: 242
Action: 3
Reward: -1
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
Timestep: 2
State: 222
Action: 3
Reward: -1
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
Timestep: 3
State: 122
Action: 1
Reward: -1
+---------+
|R: | : :G|
| : | :